### ISSUE TITLE
Language Addition: Solidity 

### ISSUE THREAD

**Issue by RyRy79261** [itchyny/fastinvsqrt#6]
## Current findings
Currently there's a few implementations that work using bytes32 or by splitting the sign, exponent & mantissa for bitwise operations however no full implementation appears to be complete.

https://github.com/BANKEX/solidity-float-point-calculation/blob/master/contracts/FloatMath.sol 
https://github.com/cag/solidity-float-point-calculation

Current suggestions is to use the Babylonian method of finding a root:
```
function sqrt(uint x) returns (uint y) {
        if (x == 0) return 0;
        else if (x <= 3) return 1;
        uint z = (x + 1) / 2;
        y = x;
        while (z < y)
        /// @why3 invariant { to_int !_z = div ((div (to_int arg_x) (to_int !_y)) + (to_int !_y)) 2 }
        /// @why3 invariant { to_int arg_x < (to_int !_y + 1) * (to_int !_y + 1) }
        /// @why3 invariant { to_int arg_x < (to_int !_z + 1) * (to_int !_z + 1) }
        /// @why3 variant { to_int !_y }
        {
            y = z;
            z = (x / z + z) / 2;
        }
    }```

**Comment by itchyny** [comment]
Patches welcome. But I prefer implementation using the magic number 0x5f3759df.

**Comment by RyRy79261** [comment]
@itchyny I was trying to find a solve using the magic number reference, was reading about it here: http://www.lomont.org/Math/Papers/2003/InvSqrt.pdf

I'm sadly not at a level to understand that paper but essentially if there was a bitwise version to finding the root rather than anything that uses loops it would be super useful. 

If I find a solve I'll update here
